### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raj292**
Added a short description on importance of Password Managers

### CODE REVIEW

**Review by Martchus — CHANGES_REQUESTED** [review]
And Hacktoberfest hasn't even started yet. Or has it already considering timezones?

Nevertheless, I suppose adding such a statement shouldn't hurt. It should, however, not appear before the first heading. And even then it seems a bit weird. Wouldn't a user which finds that project already know what a password manager is because he was searching for one? In my opinion it would make much more sense to make the work "password manager" in the first sentence a link to https://en.wikipedia.org/wiki/Password_manager.

**Comment by raj292** [comment]
> And Hacktoberfest hasn't even started yet. Or has it already considering timezones?
> 
> Nevertheless, I suppose adding such a statement shouldn't hurt. It should, however, not appear before the first heading. And even then it seems a bit weird. Wouldn't a user which finds that project already know what a password manager is because he was searching for one? In my opinion it would make much more sense to make the work "password manager" in the first sentence a link to https://en.wikipedia.org/wiki/Password_manager.

Hey! I apologise for not thinking that through. Would you require any documentation changes apart from this? I'm doing this for the first time and don't have much knowledge. 
Sorry for the inconvenience.

**Comment by Martchus** [comment]
Actually, "Password Manager" is the (not very creative) name of this project and "password manager" the actual English word explained by the Wikipedia article (mind the case). Hence I'd rather make "password manager" within the first sentence the link. For the learning experience I'd suggest to squash and force-push the commits. Otherwise I'll do it via GitHub.

**Comment by raj292** [comment]
> Actually, "Password Manager" is the (not very creative) name of this project and "password manager" the actual English word explained by the Wikipedia article (mind the case). Hence I'd rather make "password manager" within the first sentence the link. For the learning experience I'd suggest to squash and force-push the commits. Otherwise I'll do it via GitHub.

On it

**Pull request merged**
